"""Small bootstrap alias set for instrument search.

The seed is intentionally small. xtdata cache records override or merge with it
after refresh.
"""

from __future__ import annotations

from typing import Any


def seed_records(now: str) -> list[dict[str, Any]]:
    return [
        {
            "code": "600118.SH",
            "market": "SH",
            "name": "中国卫星",
            "aliases": ["中国卫星", "航天卫星"],
            "pinyin_initials": ["ZGWX", "HTWX"],
            "ascii_aliases": ["ZGWX"],
            "instrument_type": "stock",
            "sectors": ["seed"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "688234.SH",
            "market": "SH",
            "name": "天岳先进",
            "aliases": ["天岳", "天岳先进"],
            "pinyin_initials": ["TYXJ", "TY"],
            "ascii_aliases": ["TY", "TYXJ"],
            "instrument_type": "stock",
            "sectors": ["seed"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "513100.SH",
            "market": "SH",
            "name": "纳指ETF",
            "aliases": ["纳指", "纳斯达克", "纳斯达克100", "NASDAQ", "NASDAQ100", "NDX"],
            "pinyin_initials": ["NZETF", "NSDK", "NSDK100"],
            "ascii_aliases": ["NZ", "NZETF", "NASDAQ", "NASDAQ100", "NDX"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 800000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "159941.SZ",
            "market": "SZ",
            "name": "纳指ETF",
            "aliases": ["纳指", "纳斯达克", "纳斯达克100", "NASDAQ", "NASDAQ100", "NDX"],
            "pinyin_initials": ["NZETF", "NSDK", "NSDK100"],
            "ascii_aliases": ["NZ", "NZETF", "NASDAQ", "NASDAQ100", "NDX"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 300000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "513130.SH",
            "market": "SH",
            "name": "恒生科技ETF",
            "aliases": ["恒生科技", "恒生科技ETF", "港股科技", "香港科技"],
            "pinyin_initials": ["HSKJ", "HSKJETF", "GGKJ", "XGKJ"],
            "ascii_aliases": ["HSKJ", "HSKJETF"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 800000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "510300.SH",
            "market": "SH",
            "name": "沪深300ETF",
            "aliases": ["沪深300", "沪深300ETF", "HS300", "CSI300"],
            "pinyin_initials": ["HS300ETF", "HS300"],
            "ascii_aliases": ["HS300", "HS300ETF", "CSI300"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 1000000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "000300.SH",
            "market": "SH",
            "name": "沪深300",
            "aliases": ["沪深300指数", "HS300", "CSI300"],
            "pinyin_initials": ["HS300", "HS300ZS"],
            "ascii_aliases": ["HS300", "CSI300"],
            "instrument_type": "index",
            "sectors": ["seed", "沪深指数"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "510500.SH",
            "market": "SH",
            "name": "中证500ETF",
            "aliases": ["中证500", "中证500ETF", "中证500ETF南方", "CSI500", "ZZ500"],
            "pinyin_initials": ["ZZ500", "ZZ500ETF"],
            "ascii_aliases": ["CSI500", "ZZ500", "ZZ500ETF"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 2000000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "512500.SH",
            "market": "SH",
            "name": "中证500ETF",
            "aliases": ["中证500", "中证500ETF", "中证500ETF华夏", "CSI500", "ZZ500"],
            "pinyin_initials": ["ZZ500", "ZZ500ETF"],
            "ascii_aliases": ["CSI500", "ZZ500", "ZZ500ETF"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 500000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
        {
            "code": "159922.SZ",
            "market": "SZ",
            "name": "中证500ETF",
            "aliases": ["中证500", "中证500ETF", "中证500ETF嘉实", "CSI500", "ZZ500"],
            "pinyin_initials": ["ZZ500", "ZZ500ETF"],
            "ascii_aliases": ["CSI500", "ZZ500", "ZZ500ETF"],
            "instrument_type": "etf",
            "sectors": ["seed", "沪深ETF"],
            "quote_supported": "true",
            "metadata_source": "seed",
            "updated_at": now,
            "liquidity": {"avg_amount_20d": 300000000.0, "metrics_source": "seed", "metrics_updated_at": now},
            "size": {},
            "raw_fields": {},
        },
    ]
