import type { LocalizedText, StoryScene } from "./types";

const text = (zh: string, en: string): LocalizedText => ({ "zh-CN": zh, en });

export const storyScenes: StoryScene[] = [
  {
    id: "demand",
    order: 1,
    icon: "MessageSquare",
    availability: "ready",
    title: text("提出需求", "Ask QMT"),
    userMessage: text("帮我找一个流动性最好的中证500 ETF，再看看近期走势。", "Find the most liquid CSI 500 ETF and show its recent trend."),
    assistantLead: text("我会先拆解目标和筛选口径，再决定需要调用的行情工具。", "I will clarify the instrument and ranking criteria before choosing market-data tools."),
    tools: [
      {
        name: "qmt_xtdata_resolve_instrument",
        state: "success",
        summary: text("识别指数主题：中证500", "Resolved index theme: CSI 500"),
        detail: text('query="中证500" · types=["index","etf"]', 'query="CSI 500" · types=["index","etf"]'),
      },
    ],
    conclusion: text("需求已拆成“找候选、严格过滤、按实时流动性排序、查看走势”四步。", "The request is now a four-step flow: recall, strict filtering, live liquidity ranking, and chart review."),
    schema: "qmt_mcp_story_intent_v1",
    renderer: "demand",
    presentation: "conversation",
  },
  {
    id: "search",
    order: 2,
    icon: "Search",
    availability: "ready",
    title: text("搜索标的", "Resolve instrument"),
    userMessage: text("ZGWX 是哪只股票？", "Which stock does ZGWX refer to?"),
    assistantLead: text("我会同时匹配名称、代码、别名和拼音首字母，避免猜代码。", "I will match names, codes, aliases, and pinyin initials instead of guessing a symbol."),
    tools: [
      {
        name: "qmt_xtdata_search_instruments",
        state: "success",
        summary: text("返回 4 个候选 · 相关性排序", "4 candidates · ranked by relevance"),
        detail: text('query="ZGWX" · limit=8 · rank_by="relevance"', 'query="ZGWX" · limit=8 · rank_by="relevance"'),
      },
      {
        name: "qmt_xtdata_resolve_instrument",
        state: "success",
        summary: text("已解析 600118.SH 中国卫星", "Resolved 600118.SH China Spacesat"),
        detail: text("confidence=0.98 · matched_by=pinyin_initials", "confidence=0.98 · matched_by=pinyin_initials"),
      },
    ],
    conclusion: text("ZGWX 高置信度对应 600118.SH 中国卫星，后续工具可以直接使用该代码。", "ZGWX resolves to 600118.SH with high confidence, so later tools can use the exact code."),
    schema: "qmt_mcp_instrument_search_v1",
    renderer: "search",
    presentation: "confirmation",
  },
  {
    id: "kline",
    order: 3,
    icon: "ChartCandlestick",
    availability: "ready",
    title: text("K线分析", "K-line analysis"),
    userMessage: text("帮我看看天岳先进最近走势。", "Show me the recent trend for Tianyue Advanced."),
    assistantLead: text("我先确认标的代码，再读取最近 120 根日线。", "I will resolve the symbol, then load the latest 120 daily bars."),
    tools: [
      {
        name: "qmt_xtdata_resolve_instrument",
        state: "success",
        summary: text("688234.SH 天岳先进", "688234.SH Tianyue Advanced"),
        detail: text('query="天岳先进" · resolved=true · confidence=1.00', 'query="Tianyue Advanced" · resolved=true · confidence=1.00'),
      },
      {
        name: "qmt_xtdata_kline_chart",
        state: "success",
        summary: text("120 bars · 日线 · 前复权", "120 bars · daily · forward adjusted"),
        detail: text('code="688234.SH" · period="1d" · count=120 · dividend_type="front"', 'code="688234.SH" · period="1d" · count=120 · dividend_type="front"'),
      },
    ],
    conclusion: text("近期价格沿均线震荡上行，最新收盘 136.42。可以继续比较同类标的或查看组合影响。", "Price has been trending higher around its moving averages, closing at 136.42. We can compare peers or inspect portfolio impact next."),
    schema: "qmt_mcp_chart_kline_v1",
    renderer: "kline",
    presentation: "app",
  },
  {
    id: "etf",
    order: 4,
    icon: "BarChart3",
    availability: "ready",
    title: text("ETF比较", "Compare ETFs"),
    userMessage: text("帮我搜搜看中证500最好的 ETF。", "Find the best CSI 500 ETF."),
    assistantLead: text("我会先严格过滤跟踪中证500的普通 ETF，再按实时成交额和盘口质量排序。", "I will strictly filter plain CSI 500 trackers, then rank them by live turnover and spread quality."),
    tools: [
      {
        name: "qmt_xtdata_search_instruments",
        state: "success",
        summary: text("严格过滤后 5 个候选", "5 candidates after strict filtering"),
        detail: text('query="中证500" · types=["etf"] · match_mode="underlying"', 'query="CSI 500" · types=["etf"] · match_mode="underlying"'),
      },
      {
        name: "qmt_xtdata_snapshot",
        state: "success",
        summary: text("批量快照完成 · 按成交额排序", "Batch snapshots ready · ranked by turnover"),
        detail: text("codes=5 · fields=amount,bid1,ask1,volume", "codes=5 · fields=amount,bid1,ask1,volume"),
      },
    ],
    conclusion: text("510500.SH 的成交额和盘口深度领先，可作为默认首选；512500.SH 是次选。", "510500.SH leads on turnover and depth, making it the default choice; 512500.SH is the runner-up."),
    schema: "qmt_mcp_etf_comparison_v1",
    renderer: "etf",
    presentation: "app",
  },
  {
    id: "portfolio",
    order: 5,
    icon: "ShieldCheck",
    availability: "permission",
    title: text("组合风险", "Portfolio risk"),
    userMessage: text("我现在的持仓主要风险是什么？", "What are the main risks in my current portfolio?"),
    assistantLead: text("这需要只读账户权限。我会汇总持仓、行业集中度和单一标的暴露，不执行交易。", "This needs read-only account permission. I will summarize holdings, concentration, and single-name exposure without trading."),
    tools: [
      {
        name: "qmt_portfolio_positions",
        state: "permission",
        summary: text("原型数据 · 需要 xttrade 账户权限", "Fixture data · xttrade account permission required"),
        detail: text("read_only=true · account=fixture", "read_only=true · account=fixture"),
      },
      {
        name: "qmt_portfolio_risk_checks",
        state: "permission",
        summary: text("集中度与回撤阈值检查", "Concentration and drawdown threshold checks"),
        detail: text("single_name_limit=25% · sector_limit=45%", "single_name_limit=25% · sector_limit=45%"),
      },
    ],
    conclusion: text("原型组合的主要风险是科技行业集中度偏高；真实结果需要券商开放只读 xttrade 权限。", "The fixture portfolio is concentrated in technology; real results require broker-granted read-only xttrade access."),
    schema: "qmt_mcp_portfolio_risk_v1",
    renderer: "portfolio",
    presentation: "app",
  },
  {
    id: "trade",
    order: 6,
    icon: "ClipboardCheck",
    availability: "permission",
    title: text("交易计划", "Trade plan"),
    userMessage: text("如果 510500 这两天低于 8.20，就帮我买入一手。", "Buy one lot of 510500 if it trades below 8.20 within two days."),
    assistantLead: text("我可以先生成受约束的交易计划供确认；当前版本不会提交订单。", "I can prepare a guarded plan for confirmation; this version will not submit an order."),
    tools: [
      {
        name: "proposed:qmt_xttrade_conditional_plan",
        state: "permission",
        summary: text("拟议工具 · 等待交易权限与安全评审", "Proposed tool · pending trading permission and safety review"),
        detail: text("execution=false · confirmation=required · audit=required", "execution=false · confirmation=required · audit=required"),
        proposed: true,
      },
    ],
    conclusion: text("计划只会在价格、有效期、账户白名单和人工确认全部满足后才具备执行资格。当前仅展示产品原型。", "The plan would be eligible only after price, expiry, account allowlist, and human confirmation checks. This is a product prototype only."),
    schema: "proposed_qmt_trade_plan_v1",
    renderer: "trade",
    presentation: "app",
  },
  {
    id: "recovery",
    order: 7,
    icon: "RefreshCw",
    availability: "recovery",
    title: text("异常恢复", "Recover errors"),
    userMessage: text("为什么图表没有出来？", "Why did the chart not appear?"),
    assistantLead: text("我会先检查 MCP 与 QMT 行情就绪状态，再给出可操作的恢复步骤。", "I will check MCP and QMT market-data readiness, then provide an actionable recovery path."),
    tools: [
      {
        name: "qmt_health",
        state: "error",
        summary: text("xtdata 未就绪 · QMT 等待登录", "xtdata not ready · QMT awaiting login"),
        detail: text("mcp=ready · qmt=login_required · xtdata=degraded", "mcp=ready · qmt=login_required · xtdata=degraded"),
      },
    ],
    conclusion: text("完成 QMT 人工登录后重新检查即可恢复，无需重建服务或修改客户端配置。", "After signing in to QMT, retry the readiness check; no service rebuild or client reconfiguration is needed."),
    schema: "qmt_mcp_health_v1",
    renderer: "recovery",
    presentation: "status",
  },
];
